version: "3"

services: 
    es01:
        container_name: es01
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        environment: 
            - discovery.type=single-node
        ports: 
            - 9200:9200
            - 9300:9300
        networks:
            - esnet

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.12.1
        environment: 
            - ELASTICSEARCH_HOSTS=http://es01:9200
        ports: 
            - 5601:5601
        networks:
            - esnet
        
networks:
    esnet: