version: "3"
services:
    web:
        image: httpd
        ports:
            - "80:80"
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24224
                tag: httpd.access
        networks: 
            - esfluentd
  
    fluentd:
        build: ./fluentd
        volumes:
            - ./fluentd/conf:/fluentd/etc
        ports:
            - "24224:24224"
            - "9880:9880"
            - "24224:24224/udp"
        networks: 
            - esfluentd
  
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        environment:
            - "discovery.type=single-node"
        expose:
            - "9200"
        ports:
            - "9200:9200"
        networks: 
            - esfluentd
  
    kibana:
        image: docker.elastic.co/kibana/kibana:7.12.1
        ports:
            - "5601:5601"
        networks: 
            - esfluentd

networks: 
    esfluentd: